on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Run Unit tests.
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make test

    - name: goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: curl -sL https://git.io/goreleaser | bash
      if: success()
